/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./components/UserInfo/test2 copy 2.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    Carousel: typeof import('./components/Carousel.vue')['default']
    copy: typeof import('./components/UserCard copy.vue')['default']
    Countdown: typeof import('./components/Countdown.vue')['default']
    CourseTable: typeof import('./components/CourseTable.vue')['default']
    DatePicker: typeof import('./components/DatePicker.vue')['default']
    Dy: typeof import('./components/UserInfo/dy.vue')['default']
    DY: typeof import('./components/UserInfo/DY.vue')['default']
    Heisi: typeof import('./components/Heisi.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    User: typeof import('./components/User.vue')['default']
    UserAppCard: typeof import('./components/UserAppCard.vue')['default']
    UserCard: typeof import('./components/UserCard.vue')['default']
    UserInfoCard: typeof import('./components/UserInfoCard.vue')['default']
    UserSoicalCard: typeof import('./components/UserSoicalCard.vue')['default']
    WaterFall: typeof import('./components/Layout/WaterFall.vue')['default']
    Wb: typeof import('./components/UserInfo/wb.vue')['default']
    WB: typeof import('./components/UserInfo/WB.vue')['default']
    Work: typeof import('./components/Work.vue')['default']
    XHS: typeof import('./components/UserInfo/XHS.vue')['default']
  }
}
